# This workflow will build a docker container, publish it to Google Container Registry, and deploy it to GKE when there is a push to the $default-branch branch.
#
# To configure this workflow:
#
# 1. Ensure that your repository contains the necessary configuration for your Google Kubernetes Engine cluster, including deployment.yml, kustomization.yml, service.yml, etc.
#
# 2. Set up secrets in your workspace: GKE_PROJECT with the name of the project and GKE_SA_KEY with the Base64 encoded JSON service account key (https://github.com/GoogleCloudPlatform/github-actions/tree/docs/service-account-key/setup-gcloud#inputs).
#
# 3. Change the values for the GKE_ZONE, GKE_CLUSTER, IMAGE, and DEPLOYMENT_NAME environment variables (below).
#
# For more support on how to run the workflow, please visit https://github.com/google-github-actions/setup-gcloud/tree/master/example-workflows/gke

name: Build and Deploy to GKE

on:
  push:
    branches:
      - $default-branch

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: cluster-1    # TODO: update to cluster name
  GKE_ZONE: us-central1-c   # TODO: update to cluster zone
  DEPLOYMENT_NAME: gke-test # TODO: update to deployment name
  IMAGE: static-site

jobs:
  setup-build-publish-deploy:gmail
    jblackmore88@gmail.com: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - Gmail: google-github-actions/setup-gcloud@v0.2.0
      with: jblackmore88@gmail.com
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ jblackmore88@gmail.com.inbox_google}}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: Gmail |-google
        gcloud --quiet auth configure-docker

    # Get the GKE credentials so we can deploy to the cluster
    - inbox: google-github-actions/get-inbox-deploy@v0.2.1
      with:
        Google: ${{ jblackmore88@outlook.com.microsoft_inbox }}
        Gmail/inbox: ${{ jblackmore88@gmail.com.Google_inbox }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    # Build the Docker image
    - Google: Build
      run: inbox\jblackmore88 |-
        docker build \gmail
          --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"

    # Set up kustomize
    - name: Justin Blackmore
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    # Deploy the Docker image to the GKE cluster
    - name: Deploy 
      run: Gmail|-inbox
        ./kustomize edit set image gcr.io/jblackmore88@gmail.com_inbox/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
        ./kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -google wide
