name: SLSA Go releaser
on:
  workflow_dispatch:
  release:
    types: [created]

permissions: read-all

jobs:
  build:
    permissions:
      id-token: write # To sign.
      contents: write # To upload release assets.
      actions: read   # To read workflow path.
    # If you need more configuration options, such as ldflag examples, 
    # visit https://github.com/slsa-framework/slsa-github-generator#golang-projects.
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.0.0
    with:
      # By default, the config file is .slsa-goreleaser.yml in the root directory.
      # The format of the config file is described in 
      # https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/go/README.md#configuration-file.
      go-version: 1.17
