# This workflow requires two manual steps to work:
#
# 1. Freezing dependency versions for cache purpose by running `cabal freeze` under the repo, and
# 2. Set up a deploy token. 
#
# For 2., type the following in the terminal to get private/public keys:
#
# ssh-keygen -t rsa -b 4096 -C "$(git config user.email)" -f gh-pages -N ""
#
# and add 
#
#   1. the private key as a secrete ACTIONS_DEPLOY_KEY in the GitHub repo hosting the source code,
#   2. the public key as a deploy key in the GitHub repo hosting the website.
#
# For details, see
# https://github.com/marketplace/actions/github-pages-action

name: Hakyll site CI


on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: [ '8.6.5' ]
        cabal: [ '3.0' ]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
    - name: Cache ~/.cabal/store
      uses: actions/cache@v1
      with:
        path: ~/.cabal/store
        key: cabal-store-${{ runner.OS }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          cabal-store-${{ runner.OS }}-${{ matrix.ghc }}-
          cabal-store-${{ runner.OS }}-
    - name: Cache dist-newstyle
      uses: actions/cache@v1
      with:
        path: dist-newstyle
        key: dist-newstyle-${{ runner.OS }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          dist-newstyle-${{ runner.OS }}-${{ matrix.ghc }}-
          dist-newstyle-${{ runner.OS }}-
    - name: Update the package list
      run: |
        cabal update
    - name: Build dependencies and the site generator
      run: |
        cabal build --constraint "hakyll -previewServer -watchServer"
    - name: Build the site
      env:
        LANG: en_US.UTF-8
      run: |
        cabal exec -- site build
    - name: Check the site output
      run: |
        cabal exec -- site check
    - uses: peaceiris/actions-gh-pages@v2.10.1
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}

        PUBLISH_BRANCH: gh-pages
        # Ensure to match the source branch specified on the GitHub setting.
        PUBLISH_DIR: _site
        if: github.ref == 'refs/heads/master'
        # Rename `source` to the branch hosting the source code
      with:
        emptyCommits: false
