# This workflow will do a clean install of MSYS2 environment and build the source code on it
# For more information see: https://www.msys2.org/docs/ci/

name: MSYS2

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
      - name: 'Deploy'
        run: |
          echo "We're on MSYS2 environment!"
          ./your_msys2_deploy_script.sh
