# This workflow installs the latest version of Nix and runs nix-build
# on your source code. This workflow runs on push and pull events.
# Documentation for Nix is available at: https://nixos.org/

name: Nix

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10

    - name: Build
      run: nix-build
