name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

  with:
    node-version: '12.13.1'
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
