# This workflow will run PowerShell tests on Windows, Linux and macOS

name: PowerShell module

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    name: Module imports on all platforms
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Perform one Pester test to ensure files or folders are in the current directory
      shell: pwsh
      run: Get-ChildItem | Should -Not -BeNullOrEmpty
    - name: Perform two Pester tests to ensure expected results
      shell: pwsh
      run: |
        Get-ChildItem | Select-Object -ExpandProperty Name -First 1 | Should -Be '.github'
        Get-Module Pester -ListAvailable | Measure-Object | Select -ExpandProperty Count | Should -BeGreaterThan 0
    - name: Run a script in the tests directory that has advanced Pester testing 
      shell: pwsh
      run: ./tests/pester.ps1