name: Test Comment

on:
  pull_request:

jobs:
  validate-categories:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Comment on PR
        uses: unsplash/comment-on-pr@d1a1d5dd1eb1bb657a01f4d92dd5e4d5bb7857d3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: |
                test
                this is a new line
          check_for_duplicate_msg: true
