name: Test Comment

on:
  pull_request:

jobs:
  validate-categories:
    runs-on: ubuntu-latest
    steps:
      - name: Generate rows
        id: rows-generator
        run: |
          row1="\|row11\|row12\|"
          row2="\|row21\|row22\|"
          echo "::set-output name=content_1::$row1"
          echo "::set-output name=content_2::$row2"
      - name: Diff revision
        id: diff_rev
        shell: bash
        run: |
          MY_STRING=${{join(steps.rows-generator.outputs.*, '\n')}}
          MY_STRING="${MY_STRING//'%'/'%25'}"
          MY_STRING="${MY_STRING//$'\n'/'%0A'}"
          MY_STRING="${MY_STRING//$'\r'/'%0D'}"
          echo "::set-output name=content::$MY_STRING"
      - name: Comment on PR
        uses: unsplash/comment-on-pr@d1a1d5dd1eb1bb657a01f4d92dd5e4d5bb7857d3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: |
                :heavy_exclamation_mark: There are unrecognised categories found in the repo. Please note that using the right categories will result in better visibility and recommendation.
                |Workflow Template Id|Unrecognised Categories|
                |:----:  |:----:  |
                 ${{ steps.diff_rev.outputs.content }}
          check_for_duplicate_msg: true
