name: Validate Categories

on:
  pull_request:

jobs:
  validate-categories:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2

      - name: Install gems
        run: |
          gem install ./script/validate-categories/github-scout-0.1.1.gem

      - name: Validate Categories
        id: validate-categories
        run: |
          ruby validate.rb
        working-directory: ./script/validate-categories
      - name: Format Comment
        id: comment-format
        if: ${{steps.validate-categories.outputs.unrecognised-categories-exist == 'true' }}
        shell: bash
        run: |
          echo "::set-output name=content::${{join(steps.validate-categories.outputs.*, '%0A')}}"
      - name: Comment on PR
        if: ${{steps.comment-format.outputs.content && steps.comment-format.outputs.content != '' }}
        uses: unsplash/comment-on-pr@d1a1d5dd1eb1bb657a01f4d92dd5e4d5bb7857d3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: |
                :heavy_exclamation_mark: :heavy_exclamation_mark: There are unrecognised categories found in the following properties.json files. Please note that using the categories recognised by Github's Linguist will result in better visibility and recommendation.
                |Workflow Template Id|Unrecognised Categories|
                |:----:  |:----:  |
                 ${{ steps.comment-format.outputs.content }}
          check_for_duplicate_msg: true
          
