name: Validate Categories on PR

# read-only repo token
# no access to secrets
on:
  pull_request:

jobs:
  validate-categories:
    runs-on: ubuntu-latest

    steps:        
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2

      - name: Install gems
        run: |
          gem install ./script/validate-categories/github-scout-0.1.1.gem

      - name: Validate Categories
        id: validate-categories
        run: |
          ruby validate.rb
        working-directory: ./script/validate-categories
      - name: Format Comment
        id: comment-format
        if: ${{steps.validate-categories.outputs}}
        shell: bash
        run: |
          MY_STRING=$(cat << EOF
           :heavy_exclamation_mark: :heavy_exclamation_mark: There are unrecognised categories found in the following properties.json files. Please note that using the categories recognised by Github's Linguist will result in better visibility and recommendation.
          |Workflow Template Id|Unrecognised Categories|
          |:----:  |:----:  |
          EOF
          )
          MY_STRING="${MY_STRING//'%'/'%25'}"
          MY_STRING="${MY_STRING//$'\n'/'%0A'}"
          MY_STRING="${MY_STRING//$'\r'/'%0D'}"
          MY_STRING="${MY_STRING}\n${{join(steps.validate-categories.outputs.*, '%0A')}}"
          echo "${MY_STRING}"
          echo "::set-output name=content::$MY_STRING"

      - name: Save Validation Output 
        if: ${{steps.comment-format.outputs.content && steps.comment-format.outputs.content != '' }}
        run: |
          echo ${{ steps.comment-format.outputs.content }} 
          mkdir -p ./category_validation
          echo ${{ steps.comment-format.outputs.content }} > ./category_validation/output
          echo ${{ github.event.number }} > ./category_validation/issue_number

      - uses: actions/upload-artifact@v2
        if: ${{steps.comment-format.outputs.content && steps.comment-format.outputs.content != '' }}
        with:
          name: category_validation
          path: category_validation/